[phases.setup]
nixPkgs = [
    "php85",
    "php85Extensions.mbstring",
    "php85Extensions.pdo",
    "php85Extensions.pdo_pgsql",
    "php85Extensions.pgsql",
    "php85Extensions.fileinfo",
    "php85Extensions.tokenizer",
    "php85Extensions.xml",
    "php85Extensions.curl",
    "php85Extensions.bcmath",
    "php85Extensions.intl"
]

[phases.build]
cmds = [
    "composer install --optimize-autoloader --no-interaction",
    "npm run build"
]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=$PORT"